common-fate/terraform-aws-common-fate-deployment

main.tf, modules/authz/main.tf, modules/authz/variables.tf, modules/cognito/main.tf, modules/cognito/outputs.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf
Also fixes a bug caused by an invalid IAM document for SSM access. I've opted to give the Control Plane access to the entire SSM path - `common-fate/prod/*` by default. I think this greatly simplifies deployment and doesn't really have a security impact, especially as we recommend a dedicated account for all deployments.
=> Update authz environment variables with OIDC subjects for other services

outputs.tf
Adds an `outputs` variable containg all notable outputs from the module.
=> Improve the UX of fetching outputs from the deployment using a single variable

modules/gcp-integration/workload-identity-roles/main.tf, modules/gcp-integration/workload-identity-roles/variables.tf
Adds a module which configures all of the required Workload Identity Federation, Service Accounts, and role bindings required to connect to GCP from the AWS-based deployment.
=> add a reference IAM configuration for GCP integration

modules/gcp-integration/workload-identity-roles/main.tf, modules/gcp-integration/workload-identity-roles/variables.tf
they are all set to sensible defaults but can be overridden to avoid 409 errors.
=> add additional variables to GCP reference module to fix name collisions

modules/provisioner/main.tf, modules/provisioner/variables.tf
Adds entra config to provisioner.
Ops to use an ssm path instead of an ARN because it is consistent with how you configure integrations
=> Add support for entra to provisioner

modules/provisioner/main.tf, modules/provisioner/variables.tf
Removes validation on the `gcp_config` variable on the provisioner which required the variable to be set.
=> Fix issue where GCP config failed validation if 'null' was provided

modules/provisioner/main.tf
Fixes a reference which resulted in a map key lookup error if the `gcp_config` variable was null.
=> fix GCP variable key reference

modules/authz/main.tf
Use GRPC for the healthcheck rather than the HTTP monitoring port.
=> Fix authz GRPC healthcheck

modules/events/main.tf
Fixes the configuration for the cloudwatch log event target.
The configuration was incorrectly referencing the account default event bus.
The new configuration fixes this and also switches cloudwatch log group to have a fixed name instead of a prefix.
The original log group will be deleted but we should treat this as not having been working before due to the rule misconfiguration.
=> Fix cloudwatch event target

examples/existing_vpc/main.tf, examples/existing_vpc/variables.tf, examples/full/main.tf, examples/full/variables.tf, examples/simple/main.tf, examples/simple/variables.tf, main.tf, modules/web/main.tf, modules/web/variables.tf, variables.tf
Custom favicon is no longer supported. This PR is the removal of all references to it in the Terraform module
=> remove instances of favicon in the fe component

.changeset/cool-eels-attend.md, examples/existing_vpc/variables.tf, examples/full/variables.tf, examples/simple/variables.tf, variables.tf
By default, it should be empty so that the inline Common Fate logo SVG shows up.
=> Fix default logo URL pointing to a broken image

.changeset/purple-walls-fry.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/authz/main.tf, modules/authz/variables.tf, modules/cognito/outputs.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, modules/web/main.tf, modules/web/variables.tf, outputs.tf, variables.tf
Allows customising API URLs and CORS origins. Internally we are using these changes to run a second copy of the web UI to preview some changes against the existing APIs.
Exposes a bunch of additional outputs from the deployment to allow additional Cognito clients to be created.
=> Allow overriding API URLs

.changeset/curly-keys-dance.md, modules/aws-idc-integration/iam-roles/main.tf, modules/aws-idc-integration/iam-roles/variables.tf
these are disabled by default and can be enabled using the `permit_group_assignment` variable
=> add optional permissions for IAM Identity Center group membership management

modules/provisioner/main.tf, modules/provisioner/variables.tf
Required for the IAM Identity Center JIT group assignment integration.
=> Provisioner: add optional variable for IAM Identity Center Identity Store ID

.changeset/clever-spiders-drum.md, .changeset/serious-tips-bathe.md, .changeset/shiny-jobs-dance.md, main.tf, modules/cognito/main.tf, modules/cognito/outputs.tf, modules/provisioner/outputs.tf, outputs.tf, variables.tf
Adds a builtin deployment of the provisioner module
This will allow you to easily configure an integration to one instance of each like aws idc or gcloud.
You can still deploy the provisioner on its own to be able to connect to a second instance of one of the integrations.
on the main module the provisioner variables have been prefixed with "provisioner_" to make it clear what they are for.
This should be a non breaking change and can be upgraded to easily for existing teams, though no action is required.
I have chosen to make the ` idc_identity_store_id = string` mandatory on the main module config blocks only,  so when updating to the new configuration, this will need to be provided.
=> Add builtin provisioner

.changeset/short-keys-brush.md, variables.tf
Currently it's required which doesn't align with our getting started docs.
=> set default null value for assume role external ID

modules/aws-idc-integration/iam-roles/main.tf
Extends on the testing in https://github.com/common-fate/terraform-aws-common-fate-deployment/pull/67 to handle an additional edge case we found where Common Fate could fail to provision access if the user already has the Permission Set assigned to them.
=> add iam:GetRole to provisioner for AWS IAM IDC org root account access

modules/vpc/main.tf
#74 contained an error where the variable was not wired up to the 'vpc' module.
=> fix the nat gateway variable propagation to the 'vpc' module

.changeset/beige-planets-grin.md, main.tf, modules/database/main.tf, modules/database/variables.tf, variables.tf
allows the stack to be torn down without manually drifting the TF.
=> expose deletion protection variable for RDS database

.changeset/beige-planets-grin.md, .changeset/beige-planets-grin1.md, modules/provisioner/outputs.tf
`provisioner_task_role_arn` and `provisioner_task_role_name` both pointed to the arn. Fixed the `provisioner_task_role_name` to point to the name
=> provisioner_task_role_name fix 

.changeset/pretty-lobsters-argue-2.md, .changeset/pretty-lobsters-argue.md, main.tf, modules/alb/main.tf, modules/alb/variables.tf, outputs.tf, variables.tf
Previously, our BYOVPC deployment example required deploying each Common Fate submodule individually, e.g:
```hcl
module "alb" {
source    = "common-fate/common-fate-deployment/aws//modules/alb"
version   = "1.0.0"
namespace = var.namespace
stage     = var.stage
certificate_arns = [
var.app_certificate_arn
]
public_subnet_ids = var.public_subnet_ids
vpc_id            = var.vpc_id
}
module "control_plane_db" {
source          = "common-fate/common-fate-deployment/aws//modules/database"
version         = "1.0.0"
namespace       = var.namespace
stage           = var.stage
vpc_id          = var.vpc_id
subnet_group_id = var.database_subnet_group_id
}
module "authz_db" {
source    = "common-fate/common-fate-deployment/aws//modules/authz-database"
version   = "1.0.0"
namespace = var.namespace …
```
=> add top-level variables to improve BYOVPC support

.changeset/little-elephants-grab.md, modules/controlplane/main.tf
The log group was incorrectly configured for the worker which meant that the `cf deployment logs` command would not list any logs for the worker
=> Use the correct cloudwatch log group for the worker

.changeset/lemon-months-smell.md, modules/database/main.tf
Adds the `storage_encryption` field to the RDS instance.
=> add default AWS RDS encryption for new deployments

.changeset/neat-parents-jump.md, main.tf, modules/cognito/main.tf, modules/cognito/variables.tf, variables.tf
Adds support for configuring the web console refresh token validity, using the 'web_refresh_token_validity_duration' and 'web_refresh_token_validity_units' variables.
=> add support for customising web console refresh token validity

.changeset/large-buckets-glow.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/authz/main.tf, modules/authz/variables.tf, modules/controlplane/main.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf, modules/web/main.tf, modules/web/variables.tf
Adds the following IAM conditions to ECS roles:
```hcl
Condition = {
ArnLike = {
"aws:SourceArn" = "arn:aws:ecs:${var.aws_region}:${var.aws_account_id}:*"
}
StringEquals = {
"aws:SourceAccount" : "${var.aws_account_id}"
}
}
```
=> add additional IAM conditions on ECS roles

.changeset/eight-socks-repeat.md, main.tf, variables.tf
Fix an issue where the `namespace`, `stage`, and `log_retention` variables are not propagated to the ecs_base module.
=> Propagate the namespace, stage, and ecs_opentelemetry_collector_log_retention_in_days variables to the ecs_base module

.changeset/chilly-mails-hug.md, modules/controlplane/main.tf
This PR adds an extra listener rule that preceeds the access handler rule in priority and directs preview APIs to the control plane
=> Adds a new listener rule to redirect some RPCs to the control plane

.changeset/metal-moles-sin.md, modules/controlplane/main.tf
New granted service was added in https://github.com/common-fate/sdk/pull/103
Currently not working in production due to not having a alb rule allowing it to be called
=> add alb rule to allow new granted service

.changeset/plenty-roses-laugh.md, main.tf, modules/database/main.tf, modules/database/variables.tf, variables.tf
This PR ensures that our RDS database can be deployed to multi AZ instead of single AZ
Testing evidence:
```
Terraform will perform the following actions:
~ resource "aws_db_instance" "pg_db" {
id                                    = "db-BL3MICOLOGCWSTWJ4LHXKN7B7Y"
~ multi_az                              = false -> true
tags                                  = {}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
=> [CF-3045] enable multi_az for RDS database

.changeset/sweet-papayas-enjoy.md, main.tf, modules/database/main.tf, modules/database/variables.tf, variables.tf
Adds `rds_apply_immediately` to allow the upgrade from single to multi-AZ RDS databases to occur during a deployment, rather than waiting for a maintenance window. We currently don't configure maintenance windows in the TF stack, so the previous behaviour may catch users by surprise.
=> add rds_apply_immediately variable

.changeset/curvy-meals-thank.md, .changeset/seven-students-rule.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, modules/events/main.tf, variables.tf
Allows configuring a Common Fate deployment to emit tracing events to https://otel.commonfate.io.
Also allows providing a licence key as a string, rather than creating it outside of the stack. This makes initial deployment simpler as there is no initial bootstrapping step required.
Adds a dead-letter queue to the SQS events queue. In testing the tracing implementation I found that invalid Slack channel IDs could cause events to be retried indefinitely.
=> Add support for Managed Monitoring configuration

.changeset/thin-bears-rhyme.md, variables.tf
Enable the embedded authorization feature by default, leaving it in for one more release so that teams can switch back if required without needing to roll back their deployment
=> Enable embedded authorization by default

.changeset/nice-mugs-scream.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
Adds a variable to allow database migrations to be disabled - can be used when rolling back to a previous release after migrations have already run.
=> add variable to allow database migrations to be disabled

.changeset/dry-mangos-deliver.md, .changeset/six-dogs-happen.md, variables.tf
Includes fixes:
- Fix an issue where account name whitespace was not properly removed when using Common Fate as a Granted Profile Registry backend.
- Fix an issue preventing Grants from being migrated to the new Common Fate internal storage backend.
=> Release app version v3.13.2

.changeset/tidy-apples-sort.md, modules/cognito/main.tf
Adds the family name and given name attribute mappings.
This might will need to be tested to check that this doesn't break other sso saml integration. Or if we need to update all of the other docs to include mappings for these.
=> add family name and given name attributes to sso config

.changeset/giant-taxis-kneel.md, modules/authz/main.tf
Removes the networking associated with the graphql API which has been removed from the authz service.
=> remove graphql from authz module

outputs.tf
They weren't correctly copied to the main module.
=> Fix read-only client output references

modules/controlplane/main.tf, outputs.tf
We've migrated the Policy API from the Rust-based authz service to the Go Control Plane service. It is now being served by Connect RPC, which is interoperable with GRPC. GRPC interop requires that the Control Plane can accept HTTP/2 traffic. 
The Control Plane ALB target group uses HTTP/1 though, so the GRPC interop does not work.
This causes GRPC clients to stop working - our Validate Cedar Policy GitHub Action is one such example. Here's an example error on the latest prerelease:
This PR fixes this issue by introducing a second target group for the Control Plane which uses HTTP/2.
Built on top of #210 so that I could test both at once.
=> Use HTTP/2 for Control Plane policy endpoints

.changeset/loud-chairs-matter.md, modules/controlplane/main.tf
Our S3 Audit Log Destination requires that Common Fate assumes a role to write to the bucket.
We currently use ABAC to limit the roles that the Control Plane can assume. Specifically, the Control Plane can only assume roles that are tagged with `common-fate-integration-read-role`.
The problem though is that this requires users to tag the S3 bucket write role with `common-fate-integration-read-role`.
This is confusing, because we're writing rather than reading.
This PR adds a new tag `common-fate-allow-assume-role` which can be used instead, and is less confusing.
=> Allow 'common-fate-allow-assume-role' tag to be used for trust policies

.changeset/curly-cars-smell.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
The application no longer depends on these to be provided as environment variables.
This is a non breaking change, the variables are marked as deprecated and no longer used
=> Remove deprecated variables for slack and pagerduty

.changeset/poor-elephants-fetch.md, main.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf, variables.tf
Following on from the previous release, the provisioner now gets its configuration in a provisioning API request, and so the configuration in the infrastructure is no longer used.
This PR marks the fields as deprecated but does not remove them, which allows for easy rollbacks
=> deprecate configuring the provisioner via the infrastructure

.changeset/fast-shoes-yawn.md, modules/alb/main.tf
This should fix issues seen when requesting many entitlements during an AWS service degradation.
The provisioner retry timeouts are set at 2 minutes currently and provisioning happens synchronously.
=> Increase the default ALB idle connection timeout to 2.5 minutes

.changeset/loud-icons-sniff.md, modules/provisioner/main.tf
In our upgrade to provisioner not depending on the infrastructure configuration, the role granting access to secrets was supposed to be switched to the task role.
It was still on the execution role which prevented integrations requiring secrets to work.
=> Fix permissions for provisioner secrets access

.changeset/modern-weeks-approve.md, main.tf, modules/alb/main.tf, modules/alb/variables.tf
Removes the `distinct(var.certificate_arns)` which is causing the following error when
a dynamic app certificate is used:
```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/common-fate-deployment/modules/alb/main.tf line 86, in resource "aws_lb_listener_certificate" "additional_certs":
│   86:   for_each        = { for idx, cert_arn in local.distinct_certificates : idx => cert_arn if idx > 0 }
│     ├────────────────
│     │ local.distinct_certificates is a list of string, known only after apply
```
This is a non-breaking change, because we only use a single certificate ARN in the ALB anyway.
=> Fix a cyclic reference issue when 'app_certificate_arn' depends on another module

.changeset/honest-pants-move.md, .changeset/lemon-bananas-hide.md, .changeset/silent-donkeys-mate.md, .changeset/strong-ads-crash.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, modules/web/main.tf, modules/web/variables.tf, variables.tf
I have removed all of the deprecated variables to coincide with the new major version.
Teams have already migrated off of the provisioner and slack + pagerduty config in the previous releases and these variables were only left in as placeholders.
The least priv feature is also removed, and the hierarchy UI has been stabilised.
=> Remove deprecated variables and add changesets

.changeset/stupid-llamas-call.md, main.tf, modules/cognito/main.tf, modules/cognito/variables.tf, variables.tf
Similar to the existing `web_access_token_validity_duration` etc.
=> add Terraform variables for CLI token duration

.changeset/tall-paws-share.md, main.tf, modules/access/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
Adds variabels to the main module to configure the Access Handler, Control Plane and Worker
Also bumps the defaults for the access handler up to 512/1024
=> Expose cpu and memory variables for the ecs services

.changeset/hungry-crabs-join.md, variables.tf
We've been running managed monitoring now on multiple deployments in production for a few months.
It is a sensible default to enable because it allows Common Fate to proactively detect issues with deployments and monitor performance.
=> Enable Managed Monitoring by default

.changeset/large-years-chew.md, main.tf
Removes the hardcoded AWS provider block in the module. Fixes an issue where the module could not be destroyed due to the provider block being present.
=> Remove `aws` provider block from the module

.changeset/sixty-icons-compare.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, modules/web/main.tf, modules/web/variables.tf, variables.tf
Makes target groups to ECS services configurable, allowing additional load balancers to be added to a Common Fate deployment.
=> Configurable target groups

.changeset/odd-mails-repair.md, .changeset/warm-panthers-visit.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
Adds additional environment variables to the control plane and access handler, these previously has default values.
=> Pass builtin provisioner url to the services

.changeset/lovely-forks-work.md, variables.tf
Fixes the default value for the 'rds_instance_identifier_suffix' variable, to fix an error: 'The expression result is null' when applying the Terraform stack.
=> Fix the default value for the 'rds_instance_identifier_suffix' variable

.changeset/stale-zoos-rule.md, main.tf, modules/alerts/main.tf, modules/alerts/variables.tf, modules/database/outputs.tf
If a database suffix is used (as is the case when the database is restored from a snapshot), the RDS alarms to not reference the correct instance ID.
=> Fix monitoring variable references

.changeset/witty-brooms-warn.md, modules/alerts/outputs.tf
The key was incorrectly set to 'load_balancer_alerts'.
=> Fix the 'cloudwatch_alarm_topics' topic to correctly include database_alerts

.changeset/stupid-tools-return.md, modules/access/main.tf, modules/access/variables.tf, modules/aws-idc-integration/iam-roles/main.tf, modules/aws-idc-integration/iam-roles/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf, modules/web/main.tf, modules/web/variables.tf, variables.tf
Adds support for a permission boundary applied to all roles in the Terraform stack.
Guide for code review: confirm that the permissions boundary variable is applied to all resource "aws_iam_role" resources. I left it off the `general-purpose` submodule as that module is unused (I've raised a separate PR in #355 to delete the module entirely).
=> Add `iam_role_permission_boundary` variable

modules/aws-idc-integration/iam-roles/main.tf
Makes it clearer for cases where customers look at our source for the integration role.
=> add comment indicating why additional management account permissions are needed

.changeset/metal-drinks-occur.md, main.tf, modules/cognito/main.tf, modules/cognito/variables.tf, variables.tf
Fixes an issue where enabling IDP-initiated SAML SSO login would cause Terraform drift. You can now set the `saml_allow_idp_initiated_sign_in` variable to `true` to avoid configuration drift.
=> Add Terraform variable for IDP-initiated SAML SSO

.changeset/shiny-rules-deny.md, modules/controlplane/main.tf
This parameter is required for the delete secret feature in the console and was omitted during the initial release of the feature
=> Add ssm:DeleteParameter permissions for managing integration secrets
