main.tf, modules/access/main.tf, modules/access/variables.tf, modules/authz/main.tf, modules/authz/variables.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
also fixes an IAM policy for DynamoDB
=> Healthcheck and env var fixes

modules/events/outputs.tf, outputs.tf
Add event_bus_log_group_name to main module
=> add outputs for event bus log group

modules/provisioner/main.tf
it is no longer supported in terraform
=> remove module_variable_optional_attrs experiment flag from provisioner

main.tf, modules/authz/main.tf, modules/authz/variables.tf, outputs.tf
Adds configuration for the provisioner service account in authz
=> configure provisioner service account in authz

.changeset/wet-pears-dance.md, CHANGELOG.md, package.json
Reverts common-fate/terraform-aws-common-fate-deployment#29
=> Revert "Version Packages for main"

modules/access/main.tf, modules/authz/main.tf, modules/controlplane/main.tf, modules/database/main.tf, modules/provisioner/main.tf, modules/web/main.tf
Reverts common-fate/terraform-aws-common-fate-deployment#28
=> Revert "Upgrade rds database and remove old security groups"

.changeset/yellow-jobs-retire.md, modules/access/main.tf, modules/authz/main.tf, modules/controlplane/main.tf, modules/database/main.tf, modules/provisioner/main.tf, modules/web/main.tf
Remove old security groups and update RDS instance to enable deletion protection
=> Rds updates

.changeset/odd-mugs-speak.md, variables.tf
Specifies a default application release tag
=> specify default release tag

.changeset/slimy-cows-occur.md, modules/provisioner/main.tf
Adds okta parameter store arn to the policy allow
=> Fix okta permission ssm

.changeset/stupid-starfishes-deliver.md, main.tf, modules/controlplane/main.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf, variables.tf
Adds environment variables and provisioner config to configure the Common Fate DataStax integration.
=> Add DataStax integration

.changeset/small-lies-share.md, variables.tf
Upgrades bundled version to v3.1.0
=> update bundled version

.changeset/six-suns-bow.md, main.tf, modules/access/main.tf, modules/access/variables.tf, modules/authz/main.tf, modules/authz/variables.tf, modules/cognito/main.tf, modules/cognito/outputs.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf
Adds a slack cognito client and removes some unused environment variables from the control plane and access handler
=> Add slack cognito client

.changeset/clever-worms-refuse.md, .changeset/mighty-chefs-fail.md, variables.tf
Updates the bundled app version.
=> Update app version to v3.7.1

.changeset/large-chicken-turn.md, main.tf, modules/authz-database/main.tf, modules/authz-database/variables.tf, variables.tf
Adds variables which allow for pitr on a dynamodb table within Common Fate
=> added variables to allow for point-in-time recovery for dynamodb table

.changeset/calm-flowers-jump.md, modules/gcp-integration/workload-identity-roles/main.tf, modules/gcp-integration/workload-identity-roles/variables.tf
Updates the GCP integration module to support new use cases which require additional permissions.
=> Add support for provisioning GCP BigQuery and organization-level access

.changeset/happy-suns-reflect.md, .changeset/healthy-rivers-look.md, .changeset/hot-lies-hear.md, .changeset/late-goats-design.md, .changeset/metal-melons-grin.md, .changeset/mighty-hairs-heal.md, .changeset/olive-knives-sneeze.md, .changeset/plenty-keys-flow.md, .changeset/proud-crabs-deliver.md, .changeset/short-pandas-thank.md, .changeset/smooth-taxis-shout.md, .changeset/violet-lobsters-thank.md, variables.tf
Updates the bundled app version to v3.9.0. Includes changesets from the application changes.
=> update bundled app version to v3.9.0

.changeset/rare-kings-explain.md, main.tf, modules/access/main.tf, modules/access/variables.tf
Enables the Access Handler to connect to the RDS database
=> Enable the access handler to connect to the rds database

.changeset/rare-kings-explain.md, main.tf, modules/access/main.tf, modules/access/variables.tf
Reverts common-fate/terraform-aws-common-fate-deployment#169 as this is not required in pending release.
=> Revert "Enable the access handler to connect to the rds database"

.changeset/neat-dodos-pump-2.md, .changeset/neat-dodos-pump.md, .changeset/plenty-roses-laugh.md, .changeset/stale-meals-relate.md, variables.tf
=> update app version to v3.10.0

.changeset/olive-bees-push.md, .changeset/wise-ears-whisper.md, variables.tf
Updates the built-in application version to v3.11.1, including some web console fixes.
=> release app version v3.11.1

.changeset/dry-chairs-admire.md, .changeset/mighty-fishes-cough.md, .changeset/wise-pans-greet.md, variables.tf
Updates the built-in application version.
=> Release app version v3.11.3

.changeset/breezy-parents-fetch.md, main.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf, variables.tf
Adds Auth0 provisioning configuration.
=> Add Auth0 integration configuration

.changeset/metal-jobs-arrive.md, modules/vpc/main.tf
Adds VPC endpoints for S3 and DynamoDB.
=> add VPC endpoints for services used in the stack

.changeset/curvy-horses-push.md, .changeset/nasty-dingos-allow.md, variables.tf
Includes a fix for a Slack issue reported by a customer.
=> update bundled app version to v3.12.3

.changeset/curvy-horses-push.md
The copied changeset had an invalid package name.
=> fix changeset target to be correct package

.changeset/chilly-eagles-beg.md, variables.tf
Updates bundles application version to v3.13.3
=> Bump bundles application to v3.13.3

.changeset/curly-humans-hide.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf
Add service account oidc client ids to control plane environment
=> Add service OIDC client ids to control plane

.changeset/funny-fishes-tan.md, .changeset/hot-papayas-protect.md, variables.tf
=> update bundled app version to v4.1.1

.github/workflows/create-release-for-tag.yml
This Action extracts the changesets for the current release and formats them into the release notes
=> create a release automatically on new tags

.changeset/yellow-houses-study.md, main.tf, modules/provisioner/main.tf, modules/provisioner/variables.tf
Monitoring has been added to the provisioner, but needs some extra environment variables to work.
This Pr adds the environment variables needed by the provisioner environment to get the monitoring set up.
=> adds env vars used by xray for provisioner

.changeset/friendly-roses-smile.md, .changeset/witty-snakes-type.md, variables.tf
=> update app version to v4.2.3

.changeset/eight-humans-confess.md, .changeset/nervous-mirrors-roll.md, .changeset/spicy-items-sell.md, variables.tf
Updates the application version to v4.3.2.
=> Update app version to v4.3.2

.changeset/fluffy-laws-talk.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
Adds variables to configure Common Fate usage reporting.
=> Add usage reporting configuration

.changeset/dirty-monkeys-doubt.md, modules/cognito/emailtemplate.tf, modules/cognito/main.tf
=> Adds Common Fate styling to cognito invite email

.changeset/polite-countries-laugh.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf, variables.tf
Also wires up the sync_entra_identities_enabled variable to the controlplane module.
=> Add config var to disable Okta Sync task

.changeset/blue-dots-kick.md, .changeset/cool-worms-wonder.md, .changeset/large-socks-bow.md, .changeset/quiet-swans-exercise.md, .changeset/smart-poets-do.md, .changeset/tame-ears-drive.md, .changeset/tough-spiders-cheat.md, variables.tf
Updates the bundled app version.
=> Update app version to v4.6.4

.changeset/blue-dots-kick.md, .changeset/cool-worms-wonder.md, .changeset/large-socks-bow.md, .changeset/quiet-swans-exercise.md, .changeset/smart-poets-do.md, .changeset/tame-ears-drive.md, .changeset/tough-spiders-cheat.md, package.json
- fix package name for the changesets
- update the version so that next release has the correct version.
=> Fixes to changesets

.changeset/giant-tables-count.md, main.tf, modules/controlplane/main.tf, modules/controlplane/variables.tf
Passed these new env vars for client secrets to support the Admin API
=> Pass the client secrets to the control plane

.changeset/blue-goats-visit.md, variables.tf
Updates the built-in app version to the latest release.
=> Update app version to v4.7.1

.changeset/angry-birds-march.md, modules/alerts/outputs.tf, outputs.tf
Adds a separate output for the newly created topics that use cloudwatch notification format
=> add outputs for cloudwatch based alerting topics

.changeset/bright-carrots-applaud.md, .changeset/fuzzy-fireants-poke.md, .changeset/quiet-pillows-attend.md, .changeset/rude-wasps-accept.md, .changeset/three-bees-sparkle.md, variables.tf
Updates the built-in app version to a new patch release.
=> Update app version to v4.7.3

.changeset/bright-mails-refuse.md, modules/controlplane/main.tf
Required for the new integrations UI
=> Add namespace and stage to the control plane

.changeset/calm-crews-juggle.md, .changeset/early-knives-wave.md, .changeset/hungry-singers-invite.md, .changeset/lovely-cameras-type.md, .changeset/moody-bottles-walk.md, .changeset/twelve-snakes-push.md, variables.tf
Bumps application to 4.8.1 fixing an issue with bulk actions on the access requests table, and not syncing closed AWS accounts
=> Update application version to 4.8.3

.changeset/seven-geese-heal.md, main.tf, modules/database/main.tf, modules/database/variables.tf, variables.tf
Adds necessary fields needed for making incremental snapshot updates to the Common Fate deployment RDS database.
- snapshot_identifier
- suffix
=> added optional snapshot identifer

.changeset/swift-tips-accept.md, modules/controlplane/main.tf
Remove `assign_public_ip` which defaults to false.
=> Disabled control plane publicip

.changeset/afraid-olives-tan.md, .changeset/bright-tips-exist.md, .changeset/calm-hotels-drop.md, .changeset/empty-donkeys-smash.md, .changeset/fast-experts-exercise.md, .changeset/funny-toys-smile.md, .changeset/seven-mails-dress.md, variables.tf
Updates the built-in release tag.
=> Release app version v4.10.0

.changeset/angry-books-shout.md, main.tf
Fixes an issue where the 'iam_role_permission_boundary' variable was not correctly propagated to submodules.
=> Fix `iam_permission_boundary` variable propagation
